version: '3.8'
services:
  criteria_api:
    build: ./criteria_api
    container_name: criteria_api
    env_file:
      - ./criteria_api/.env
    ports:
      - "8000:8000"
    depends_on:
      # Add CosmosDB emulator or other dependencies here if needed
      []
    restart: unless-stopped
  candidate_api:
    build:
      context: ..  # use repo root so shared_utils is included for path dependency
      dockerfile: apps/candidate_api/Dockerfile
    container_name: candidate_api
    env_file:
      - ./candidate_api/.env
    ports:
      - "8002:8002"
    depends_on:
      []
    restart: unless-stopped
  agent:
    build: ./agent
    container_name: agent
    env_file:
      - ./agent/.env
    ports:
      - "8001:8001"
  webapp:
    build: ./webapp
    container_name: veda_webapp
    environment:
      - VITE_CRITERIA_API_URL=http://localhost:8000
    ports:
      - "5173:5173"
    depends_on:
      - criteria_api
